TARGET := dhrystone4sim

C_SRCS := dhry_stubs.c dhry_1.c dhry_2.c 
HEADERS := dhry.h

CFLAGS := -O2  -fno-inline -fno-common  -falign-functions=4


BSP_BASE = ../../bsp
include $(BSP_BASE)/$(BOARD)/env/common.mk

